import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/ui/Header";
import BannerSlider from "@/components/BannerSlider";
import ClubSection from "@/components/ClubSection";
import CallToActionOne from "@/components/CallToActionOne";
import Testimonials from "@/components/Testmonials";
import Partners from "@/components/Partners";
import CallToActionTwo from "@/components/CallToActionTwo";
import FAQ from "@/components/FAQ";
import Modal from "@/components/ui/Modal";
import { useState } from "react";
import WhatsappButton from "@/components/ui/WhatsappButton";

export default function Home() {
  const [isOpen, setIsOpen] = useState<boolean>(false)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <BannerSlider openModal={() => setIsOpen(true)} />
        <ClubSection openModal={() => setIsOpen(true)} />
        <CallToActionOne openModal={() => setIsOpen(true)} />
        <Partners />
        <Testimonials />
        <FAQ />
        <Modal
          isOpen={isOpen}
          onClose={() => setIsOpen(false)}
        />
        <WhatsappButton />
      </main>
    </>
  );
}
